spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/train_mate
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        default-page-size: 10

server:
  error:
    include-message: always
